- name: Run unit tests
  env:
    VITE_FB_API_KEY: ${{ secrets.FB_API_KEY }}
    VITE_FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
    VITE_FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
    VITE_FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
    VITE_FB_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }}
    VITE_FB_APP_ID: ${{ secrets.FB_APP_ID }}
  run: yarn test:coverage
  on:
    push:
      branches: ["master"]
